services:
  app:
    build: .
    env_file:
      - .env
    secrets:
      - slack-bot-user-oauth-token
      - database-password
    volumes:
      - data:/app/data

secrets:
  slack-bot-user-oauth-token:
    file: secrets/slack-bot-user-oauth-token
  database-password:
    file: secrets/database-password

volumes:
  data:
